### PR TITLE
Move mybinder link to Python3

### PR DESCRIPTION
**Pull request by clavin-xlnx**
Current link is broken, move to python3 setup for now.

### CODE REVIEW

**Review by eddieh-xlnx — COMMENTED** [review]
The old link does seem to be broken for me too; all I get is:
```
Found built image, launching...
Launching server...
Server requested
2023-10-30T23:45:48.091853Z [Normal] Successfully assigned ovh2/jupyter-clavin-2dxlnx-2drapidwright-2dbinder-2dd9p2hn3u to user-202211a-node-e89fa1
2023-10-30T23:45:48Z [Normal] Container image "jupyterhub/mybinder.org-tc-init:2020.12.4-0.dev.git.4289.h140cef52" already present on machine
2023-10-30T23:45:49Z [Normal] Created container tc-init
2023-10-30T23:45:49Z [Normal] Started container tc-init
2023-10-30T23:45:50Z [Normal] Pulling image "2lmrrh8f.gra7.container-registry.ovh.net/mybinder-builds/r2d-g5b5b759clavin-2dxlnx-2drapidwright-2dbinder-97a58d:24527f33b6aea283cf430ab8f4eab3dc01fa5d64"
```
in the "Build logs" and then stalls for a very long time before retrying.

Are you seeing the same?

**Comment by clavin-xlnx** [comment]
> Are you seeing the same?

Yes, that is the purpose of this PR--get something working for now.

**Comment by clavin-xlnx** [comment]
Does this new link work for you?
https://mybinder.org/v2/gh/clavin-xlnx/RapidWright-binder/python3?urlpath=%2Fnotebooks%2FHelloWorld.ipynb

**Comment by eddieh-xlnx** [comment]
> Does this new link work for you? https://mybinder.org/v2/gh/clavin-xlnx/RapidWright-binder/python3?urlpath=%2Fnotebooks%2FHelloWorld.ipynb

This eventually worked for me, but it's not clear whether it was because you gave me a new link or whether I got lucky.

**Review by eddieh-xlnx — APPROVED** [review]
I just tried what I think is the latest link:
```
https://mybinder.org/v2/gh/clavin-xlnx/RapidWright-binder/python3-no-docker?labpath=HelloWorld.ipynb
```
it sat there spinning for a long time, but seemed to eventually complete. Then when I tried it again, it seemed to work almost instantaneously (due to caching?).

Other than that, it worked for me.

**Comment by clavin-xlnx** [comment]
> I just tried what I think is the latest link:
> 
> ```
> https://mybinder.org/v2/gh/clavin-xlnx/RapidWright-binder/python3-no-docker?labpath=HelloWorld.ipynb
> ```
> 
> it sat there spinning for a long time, but seemed to eventually complete. Then when I tried it again, it seemed to work almost instantaneously (due to caching?).
> 
> Other than that, it worked for me.

I think mybinder.org is under served by resources right now, so quality might be hit-or-miss.  I think this is likely the best we can have for now and is an improvement from what we currently have anyway.

**Pull request merged**
