### PR TITLE
Add initial constants schema.

### PR DESCRIPTION
**Pull request by litghost**

### CODE REVIEW

**Comment by daveshah1** [comment]
LGTM.

Although somewhat separate from this, something else that would be useful is information on the constant that a cell pin should be connected to, if it is left unconnected in the netlist.

**Comment by litghost** [comment]
> LGTM.
> 
> Although somewhat separate from this, something else that would be useful is information on the constant that a cell pin should be connected to, if it is left unconnected in the netlist.

That is actually part of the Cell <-> BEL pin mapping.

**Comment by litghost** [comment]
Remaining work on this PR:
 - [ ] Add wires using https://www.rapidwright.io/javadoc/com/xilinx/rapidwright/device/Node.html#isTied-- and friends
 - [ ] Add BELs matching on BEL type == "HARD0" and == "HARD1"
  - [ ] Use API once added

**Comment by litghost** [comment]
This PR is blocked by a fix for #104

**Comment by litghost** [comment]
The current tied wires encoding isn't good enough, or there is a database error.  Looking into it.

**Comment by litghost** [comment]
Ok, this is ready for review.

**Review by clavin-xlnx — APPROVED** [review]
Looks good to me.

**Pull request merged**
