### PR TITLE
UltraScale Incremental Clock Router

### PR DESCRIPTION
**Pull request by clavin-xlnx**
Assumes the horizontal distribution lines are already in place, a common technique in DFX designs.

### CODE REVIEW

**Comment by eddieh-xlnx** [comment]
Would it be straightforward to generate a test for this?

**Comment by clavin-xlnx** [comment]
> Would it be straightforward to generate a test for this?

If we had a design that had the need, possibly yes.

**Comment by eddieh-xlnx** [comment]
> If we have a design that had the need, possibly yes.

I was more alluding to -- do you recall what testcase you used to build this feature?

I have a bigger (and the original non-public) testcase that drove this work, but is it straightforward to manufacture a public, clock-specific testcase?

**Comment by clavin-xlnx** [comment]
> I have a bigger (and the original non-public) testcase that drove this work, but is it straightforward to manufacture a public, clock-specific testcase?

The only existing DCP in test/RapidWrightDCP that comes close is the microblaze design, but it targets UltraScale. Because it is missing the leaf clock buffers, this code doesn't work for that design scenario.  I would have to retarget it to UltraScale+.

**Comment by clavin-xlnx** [comment]
Add a test case for incremental clock routing on UltraScale+.

**Pull request merged**
