### PR TITLE
Add recursive partitioning ternary tree (RPTT)

### PR DESCRIPTION
**Pull request by diriLin**

### CODE REVIEW

**Comment by eddieh-xlnx** [comment]
This PR brings in the Recursive Partition Ternary Tree technique as described in:
```bibtex
@inproceedings{zang2024parallel,
  title={An Open-Source Fast Parallel Routing Approach for Commercial FPGAs},
  author={Zang, Xinshi and Lin, Wenhao and Lin, Shiju and Liu, Jinwei and Young, Evangeline FY},
  booktitle={Proceedings of the Great Lakes Symposium on VLSI 2024},
  year={2024}
}
```

**Comment by clavin-xlnx** [comment]
This PR is causing an out of memory exception in our regression tests:
```
Caused by: java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.IdentityHashMap.init(IdentityHashMap.java:257)
	at java.base/java.util.IdentityHashMap.<init>(IdentityHashMap.java:213)
	at com.xilinx.rapidwright.rwroute.RouteNode.incrementDriver(RouteNode.java:551)
	at com.xilinx.rapidwright.rwroute.RWRoute.buildDriverCountsOfRnodes(RWRoute.java:1433)
	at com.xilinx.rapidwright.rwroute.RWRoute.findIllegalRoutes(RWRoute.java:1411)
	at com.xilinx.rapidwright.rwroute.RWRoute.fixRoutes(RWRoute.java:1387)
	at com.xilinx.rapidwright.rwroute.RWRoute.postRouteProcess(RWRoute.java:1009)
	at com.xilinx.rapidwright.rwroute.RWRoute.route(RWRoute.java:803)
	at com.xilinx.rapidwright.rwroute.RWRoute.routeDesign(RWRoute.java:2244)
	at com.xilinx.rapidwright.rwroute.CUFR.routeDesignWithUserDefinedArguments(CUFR.java:174)
	at com.xilinx.rapidwright.rwroute.TestRWRoute.testFullRoutingWithCUFR(TestRWRoute.java:193)
```
Can we use a smaller design or do anything to reduce the memory footprint?

**Comment by eddieh-xlnx** [comment]
> This PR is causing an out of memory exception in our regression tests:
> 
> ```
> Caused by: java.lang.OutOfMemoryError: Java heap space
> 	at java.base/java.util.IdentityHashMap.init(IdentityHashMap.java:257)
> 	at java.base/java.util.IdentityHashMap.<init>(IdentityHashMap.java:213)
> 	at com.xilinx.rapidwright.rwroute.RouteNode.incrementDriver(RouteNode.java:551)
> 	at com.xilinx.rapidwright.rwroute.RWRoute.buildDriverCountsOfRnodes(RWRoute.java:1433)
> 	at com.xilinx.rapidwright.rwroute.RWRoute.findIllegalRoutes(RWRoute.java:1411)
> 	at com.xilinx.rapidwright.rwroute.RWRoute.fixRoutes(RWRoute.java:1387)
> 	at com.xilinx.rapidwright.rwroute.RWRoute.postRouteProcess(RWRoute.java:1009)
> 	at com.xilinx.rapidwright.rwroute.RWRoute.route(RWRoute.java:803)
> 	at com.xilinx.rapidwright.rwroute.RWRoute.routeDesign(RWRoute.java:2244)
> 	at com.xilinx.rapidwright.rwroute.CUFR.routeDesignWithUserDefinedArguments(CUFR.java:174)
> 	at com.xilinx.rapidwright.rwroute.TestRWRoute.testFullRoutingWithCUFR(TestRWRoute.java:193)
> ```

Ooh, where did you get this stack trace from? I couldn't find it in the GHA logs nor reproduce it locally even when I restrict the heap size.

**Comment by clavin-xlnx** [comment]
> Ooh, where did you get this stack trace from? I couldn't find it in the GHA logs nor reproduce it locally even when I restrict the heap size.

I got this from the latest regression run:
https://github.com/Xilinx/RapidWright/actions/runs/10391715887?pr=1049

You have to download the "Java Test Report" at the bottom of the page, unzip it and load the `index.html` into a browser.  The full trace looks like this: 

image

**Comment by eddieh-xlnx** [comment]
> Can we use a smaller design or do anything to reduce the memory footprint?

Turns out `ThreadLocal` can incur memory "leaks" since the only decent way for its values to get garbage collected (without killing the thread) is for the owning thread to call `ThreadLocal.remove()`. Even allowing `ThreadLocal` to be GC-ed does not guarantee its values will be GC-ed. However, by the time we know all overlaps have been resolved and we're done routing, there's no practical way to cycle through all the threads to call `remove()`.

Switch to a `ConcurrentHashMap` instead -- this only gets called once per routed connection, so performance impact should not be noticeable.

**Review by clavin-xlnx — APPROVED** [review]

**Comment by eddieh-xlnx** [comment]
Looks like this got closed because the target branch was merged. @diriLin is it possible for you to re-open (otherwise you'll have to start a new PR).

**Comment by diriLin** [comment]
> Looks like this got closed because the target branch was merged. @diriLin is it possible for you to re-open (otherwise you'll have to start a new PR).

@eddieh-xlnx It seems that I cannot re-open this PR because the base branch has been deleted. I would create a new PR.

**Pull request closed without merging**
