### PR TITLE
Adds GitHub Action Smoke Test for RapidWright Wrapper

### PR DESCRIPTION
**Pull request by clavin-xlnx**

### CODE REVIEW

**Comment by eddieh-xlnx** [comment]
Can you try with the "#!/bin/bash` shebang instead?

**Comment by clavin-xlnx** [comment]
> Can you try with the `#!/bin/bash` shebang for `rapidwright` instead?

Should we try to stick to the wider compatible `/bin/sh`?  Gradle seems to handle this task in `sh` with:

https://github.com/Xilinx/RapidWright/blob/38c4b68008f3ae4cfec4e1363a4e1635688aca4a/gradlew#L27-L40

**Comment by eddieh-xlnx** [comment]
> > Can you try with the `#!/bin/bash` shebang for `rapidwright` instead?
> 
> Should we try to stick to the wider compatible `/bin/sh`? `gradlew` seems to handle this task in `sh` with:

Yes, that's a good idea. I learned there's a material difference between single bracket and double bracket today!

As for the latest failure, looks like we need to use `$0` instead of `${BASH_SOURCE}` too
https://stackoverflow.com/questions/29832037/how-to-get-script-directory-in-posix-sh

**Comment by clavin-xlnx** [comment]
> As for the latest failure, looks like we need to use `$0` instead of `${BASH_SOURCE}` too: https://stackoverflow.com/questions/29832037/how-to-get-script-directory-in-posix-sh

I reused the logic from `gradlew`, not sure if that is something we want to separate out.  I also had to restructure the script so that the `--list-apps` option to return 0 for GitHub Actions not to fail.

**Review by eddieh-xlnx — APPROVED** [review]

**Pull request merged**
