### PR TITLE
Add constant net check.

### PR DESCRIPTION
**Pull request by litghost**
@clavin-xlnx Can you run this through your test set, and see if it explodes.  I've done some initial tests and it seems to be catch the problem I wanted to detect.

### CODE REVIEW

**Comment by clavin-xlnx** [comment]
@litghost, I ran through the test set, no explosions so looks good.  One request, would you mind renaming variables to use camelCase?  If not, I can easily do it after the merge.  Thank you!

**Comment by litghost** [comment]
> One request, would you mind renaming variables to use camelCase? If not, I can easily do it after the merge. Thank you!

Ya sure.

**Comment by litghost** [comment]
> @litghost, I ran through the test set, no explosions so looks good. One request, would you mind renaming variables to use camelCase? If not, I can easily do it after the merge. Thank you!

This has been fixed.  Something to consider is makefile targets for auto-formatting and checking that formatting.  Does Java have a good auto-formatter?

**Comment by clavin-xlnx** [comment]
I need to look into finding a compatible auto-formatter, that is a good suggestion.

**Pull request merged**
